import { FormEvent, useState } from "react";
import { FilePlus2 } from "lucide-react";
import { Button } from "../../components/ui/Button";
import { Field } from "../../components/ui/Field";
import { PromptList } from "./PromptList";
import { REPORT_FORMATS, REPORT_TEMPLATES } from "./config";

/**
 * Reports are generated by the assistant (POST /chat → report_id → secure download link in the answer).
 * This form only composes that request; it does not create files itself.
 */
export function ReportsPage({ onAsk }: { onAsk: (prompt: string) => void }) {
  const [topic, setTopic] = useState("");
  const [format, setFormat] = useState<(typeof REPORT_FORMATS)[number]>("Excel");
  const [error, setError] = useState("");

  const submit = (event: FormEvent) => {
    event.preventDefault();
    const clean = topic.trim();
    if (!clean) {
      setError("Enter what the report should cover.");
      return;
    }
    setError("");
    onAsk(`Generate a report on ${clean} in ${format}`);
  };

  return (
    <div className="page">
      <div className="workspace-hero-banner">
        <h1 className="workspace-hero-title">Automated Document Reports</h1>
        <p className="page-intro">Ask Nanvi to prepare structured executive reports from data you're authorized to access. When ready, a secure verified download link appears in the answer.</p>
        <span className="workspace-meta-tag">📄 Multi-format Export (Excel, PDF, Word, PowerPoint)</span>
      </div>

      <section className="page-section" aria-labelledby="report-new">
        <h2 id="report-new">New report</h2>
        <form className="report-form" onSubmit={submit} noValidate>
          <Field
            label="Report topic"
            required
            value={topic}
            maxLength={200}
            onChange={(e) => { setTopic(e.target.value); if (error) setError(""); }}
            placeholder="For example: overdue invoices, Q1 budget"
            error={error}
          />
          <div className="field">
            <label className="field-label" htmlFor="report-format">Format</label>
            <select id="report-format" className="select" value={format} onChange={(e) => setFormat(e.target.value as typeof format)}>
              {REPORT_FORMATS.map((f) => <option key={f} value={f}>{f}</option>)}
            </select>
          </div>
          <Button type="submit" variant="primary" icon={FilePlus2} className="report-submit">Generate report</Button>
        </form>
      </section>

      <section className="page-section" aria-labelledby="report-templates">
        <h2 id="report-templates">Templates</h2>
        <PromptList prompts={REPORT_TEMPLATES} onAsk={onAsk} />
      </section>
    </div>
  );
}
