from enum import StrEnum


class Permission(StrEnum):
    FILE_READ = "FILE_READ"
    FILE_WRITE = "FILE_WRITE"
    EMAIL_READ = "EMAIL_READ"
    EMAIL_SEND = "EMAIL_SEND"
    DATABASE_READ = "DATABASE_READ"
    DATABASE_WRITE = "DATABASE_WRITE"
    REPORT_CREATE = "REPORT_CREATE"
    REPORT_DOWNLOAD = "REPORT_DOWNLOAD"
    FINANCE_READ = "FINANCE_READ"
    HR_READ = "HR_READ"
    AUDIT_READ = "AUDIT_READ"
    WEB_SEARCH = "WEB_SEARCH"
    CONNECTION_READ = "CONNECTION_READ"
    CONNECTION_WRITE = "CONNECTION_WRITE"
    CONNECTION_DELETE = "CONNECTION_DELETE"
    CONNECTION_ADMIN = "CONNECTION_ADMIN"
    CONNECTION_USE = "CONNECTION_USE"
    CONNECTION_OWN_MANAGE = "CONNECTION_OWN_MANAGE"
    CONNECTION_ORG_VIEW = "CONNECTION_ORG_VIEW"
    CONNECTION_ORG_MANAGE = "CONNECTION_ORG_MANAGE"
    CONNECTION_AUDIT_VIEW = "CONNECTION_AUDIT_VIEW"


READ_PERMISSIONS = frozenset({
    Permission.FILE_READ,
    Permission.EMAIL_READ,
    Permission.DATABASE_READ,
    Permission.FINANCE_READ,
    Permission.HR_READ,
    Permission.AUDIT_READ,
    Permission.REPORT_DOWNLOAD,
    Permission.WEB_SEARCH,
    Permission.CONNECTION_READ,
    Permission.CONNECTION_ORG_VIEW,
    Permission.CONNECTION_USE,
    Permission.CONNECTION_AUDIT_VIEW,
})

WRITE_PERMISSIONS = frozenset({
    Permission.FILE_WRITE,
    Permission.EMAIL_SEND,
    Permission.DATABASE_WRITE,
    Permission.CONNECTION_WRITE,
    Permission.CONNECTION_DELETE,
    Permission.CONNECTION_ADMIN,
    Permission.CONNECTION_OWN_MANAGE,
    Permission.CONNECTION_ORG_MANAGE,
})

ALL_PERMISSIONS = frozenset(Permission)

